Added first test that relies on creating a new world class that is empty
sethpthomas91/conways-GOL-ruby pull request #1
Opened 2022-03-02 22:47 UTC by sethpthomas91

2022-03-02 23:09 UTC, scottyplunkett requested changes
Nice work getting your first PR in! Please understand feedback in a PR can often be terse, brevity is not meant to offend.   

I noticed you set this project up as a Gem, I probably threw you off with my Gem description on slack. I should have mentioned; **all Gems are ruby projects**, but **not all ruby projects need to be or use gems**. A ruby project could potentially be as simple as a single ruby file (though you _should_ always have a README as well).

Concretely:
1. Adjust the project so that it is **NOT A GEM**
2. For testing, let's use `rspec`.... It's typically the testing framework we use for testing ruby instead of minitest.... [rspec](https://rspec.info/) is a Gem, so your `Gemfile` should look something like the below:
```
source "https://rubygems.org"

gem 'rspec'
```
Don't hesitate to reach out with questions!

2022-03-03 21:24 UTC, sethpthomas91 commented
Refactored the project to not be a gem. Added two classes, Cell and World. Wrote one test for cell.

2022-03-03 22:54 UTC, scottyplunkett requested changes
In addition to the comments. I would add the `README` back to the repo with basic setup, dependencies/requirements (i.e. ruby version) & test running instructions. I would also delete the `runner.rb` until you're using it.

2022-03-03 22:54 UTC, scottyplunkett commented on Gemfile
>  git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
I don't think you need this line unless you have Gem's coming from github sources.

```suggestion
```

2022-03-03 22:54 UTC, scottyplunkett commented on .rspec
> +--require spec_helper
You can delete this file, it's not necessary.

2022-03-03 22:54 UTC, scottyplunkett commented on lib/cell.rb
> +
```suggestion
```

2022-03-03 22:54 UTC, scottyplunkett commented on spec/spec_helper.rb
> +end
You can delete this file, it's not necessary.

2022-03-03 22:54 UTC, scottyplunkett commented on Gemfile
> +
If not necessary, (here it is not, I think) I would not use the `# frozen_string_literal` directive.
```suggestion
```

2022-03-04 17:34 UTC, merged